config/routes.rb
Reflectr::Application.routes.draw do
  resources :current_stats

  resources :stats

  resources :metrics

  resources :profiles

  resources :pollgroups

  resources :data_types

  resources :devices

  resources :device_types

  resources :metric_types

end

app/models/pollgroup.rb
class Pollgroup < ActiveRecord::Base
  has_many :profiles
  has_many :metrics
  has_many :device_types, :through => :profiles
end

app/controllers/pollgroups_controller.rb
class PollgroupsController < ApplicationController
  # GET /pollgroups
  # GET /pollgroups.xml
  def index
    @pollgroups = Pollgroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pollgroups }
    end
  end

  # GET /pollgroups/1
  # GET /pollgroups/1.xml
  def show
    @pollgroup = Pollgroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pollgroup }
    end
  end

  # GET /pollgroups/new
  # GET /pollgroups/new.xml
  def new
    @pollgroup = Pollgroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pollgroup }
    end
  end

  # GET /pollgroups/1/edit
  def edit
    @pollgroup = Pollgroup.find(params[:id])
  end

  # POST /pollgroups
  # POST /pollgroups.xml
  def create
    @pollgroup = Pollgroup.new(params[:pollgroup])

    respond_to do |format|
      if @pollgroup.save
        format.html { redirect_to(@pollgroup, :notice => 'Pollgroup was successfully created.') }
        format.xml  { render :xml => @pollgroup, :status => :created, :location => @pollgroup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pollgroup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pollgroups/1
  # PUT /pollgroups/1.xml
  def update
    @pollgroup = Pollgroup.find(params[:id])

    respond_to do |format|
      if @pollgroup.update_attributes(params[:pollgroup])
        format.html { redirect_to(@pollgroup, :notice => 'Pollgroup was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pollgroup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pollgroups/1
  # DELETE /pollgroups/1.xml
  def destroy
    @pollgroup = Pollgroup.find(params[:id])
    @pollgroup.destroy

    respond_to do |format|
      format.html { redirect_to(pollgroups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pollgroups_helper.rb
module PollgroupsHelper
end

app/views/pollgroups/_form.html.erb
<%= form_for(@pollgroup) do |f| %>
  <% if @pollgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pollgroup.errors.count, "error") %> prohibited this pollgroup from being saved:</h2>

      <ul>
      <% @pollgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pollgroups/edit.html.erb
<h1>Editing pollgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @pollgroup %> |
<%= link_to 'Back', pollgroups_path %>

app/views/pollgroups/index.html.erb
<h1>Listing pollgroups</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pollgroups.each do |pollgroup| %>
  <tr>
    <td><%= pollgroup.name %></td>
    <td><%= link_to 'Show', pollgroup %></td>
    <td><%= link_to 'Edit', edit_pollgroup_path(pollgroup) %></td>
    <td><%= link_to 'Destroy', pollgroup, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pollgroup', new_pollgroup_path %>

app/views/pollgroups/new.html.erb
<h1>New pollgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', pollgroups_path %>

app/views/pollgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pollgroup.name %>
</p>


<%= link_to 'Edit', edit_pollgroup_path(@pollgroup) %> |
<%= link_to 'Back', pollgroups_path %>