config/routes.rb
Reflectr::Application.routes.draw do
  resources :current_stats

  resources :stats

  resources :metrics

  resources :profiles

  resources :pollgroups

  resources :data_types

  resources :devices

  resources :device_types

  resources :metric_types

end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  # GET /device_types
  # GET /device_types.xml
  def index
    @device_types = DeviceType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @device_types }
    end
  end

  # GET /device_types/1
  # GET /device_types/1.xml
  def show
    @device_type = DeviceType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @device_type }
    end
  end

  # GET /device_types/new
  # GET /device_types/new.xml
  def new
    @device_type = DeviceType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @device_type }
    end
  end

  # GET /device_types/1/edit
  def edit
    @device_type = DeviceType.find(params[:id])
  end

  # POST /device_types
  # POST /device_types.xml
  def create
    @device_type = DeviceType.new(params[:device_type])

    respond_to do |format|
      if @device_type.save
        format.html { redirect_to(@device_type, :notice => 'Device type was successfully created.') }
        format.xml  { render :xml => @device_type, :status => :created, :location => @device_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @device_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /device_types/1
  # PUT /device_types/1.xml
  def update
    @device_type = DeviceType.find(params[:id])

    respond_to do |format|
      if @device_type.update_attributes(params[:device_type])
        format.html { redirect_to(@device_type, :notice => 'Device type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @device_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /device_types/1
  # DELETE /device_types/1.xml
  def destroy
    @device_type = DeviceType.find(params[:id])
    @device_type.destroy

    respond_to do |format|
      format.html { redirect_to(device_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/views/device_types/_form.html.erb
<%= form_for(@device_type) do |f| %>
  <% if @device_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device_type.errors.count, "error") %> prohibited this device_type from being saved:</h2>

      <ul>
      <% @device_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/device_types/edit.html.erb
<h1>Editing device_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @device_type %> |
<%= link_to 'Back', device_types_path %>

app/views/device_types/index.html.erb
<h1>Listing device_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @device_types.each do |device_type| %>
  <tr>
    <td><%= device_type.name %></td>
    <td><%= link_to 'Show', device_type %></td>
    <td><%= link_to 'Edit', edit_device_type_path(device_type) %></td>
    <td><%= link_to 'Destroy', device_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device type', new_device_type_path %>

app/views/device_types/new.html.erb
<h1>New device_type</h1>

<%= render 'form' %>

<%= link_to 'Back', device_types_path %>

app/views/device_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @device_type.name %>
</p>


<%= link_to 'Edit', edit_device_type_path(@device_type) %> |
<%= link_to 'Back', device_types_path %>