config/routes.rb
Reflectr::Application.routes.draw do
  resources :current_stats

  resources :stats

  resources :metrics

  resources :profiles

  resources :pollgroups

  resources :data_types

  resources :devices

  resources :device_types

  resources :metric_types

end

app/controllers/metric_types_controller.rb
class MetricTypesController < ApplicationController
  # GET /metric_types
  # GET /metric_types.xml
  def index
    @metric_types = MetricType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @metric_types }
    end
  end

  # GET /metric_types/1
  # GET /metric_types/1.xml
  def show
    @metric_type = MetricType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @metric_type }
    end
  end

  # GET /metric_types/new
  # GET /metric_types/new.xml
  def new
    @metric_type = MetricType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @metric_type }
    end
  end

  # GET /metric_types/1/edit
  def edit
    @metric_type = MetricType.find(params[:id])
  end

  # POST /metric_types
  # POST /metric_types.xml
  def create
    @metric_type = MetricType.new(params[:metric_type])

    respond_to do |format|
      if @metric_type.save
        format.html { redirect_to(@metric_type, :notice => 'Metric type was successfully created.') }
        format.xml  { render :xml => @metric_type, :status => :created, :location => @metric_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @metric_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /metric_types/1
  # PUT /metric_types/1.xml
  def update
    @metric_type = MetricType.find(params[:id])

    respond_to do |format|
      if @metric_type.update_attributes(params[:metric_type])
        format.html { redirect_to(@metric_type, :notice => 'Metric type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @metric_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /metric_types/1
  # DELETE /metric_types/1.xml
  def destroy
    @metric_type = MetricType.find(params[:id])
    @metric_type.destroy

    respond_to do |format|
      format.html { redirect_to(metric_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/metric_types_helper.rb
module MetricTypesHelper
end

app/views/metric_types/_form.html.erb
<%= form_for(@metric_type) do |f| %>
  <% if @metric_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric_type.errors.count, "error") %> prohibited this metric_type from being saved:</h2>

      <ul>
      <% @metric_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metric_types/edit.html.erb
<h1>Editing metric_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @metric_type %> |
<%= link_to 'Back', metric_types_path %>

app/views/metric_types/index.html.erb
<h1>Listing metric_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @metric_types.each do |metric_type| %>
  <tr>
    <td><%= metric_type.name %></td>
    <td><%= link_to 'Show', metric_type %></td>
    <td><%= link_to 'Edit', edit_metric_type_path(metric_type) %></td>
    <td><%= link_to 'Destroy', metric_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Metric type', new_metric_type_path %>

app/views/metric_types/new.html.erb
<h1>New metric_type</h1>

<%= render 'form' %>

<%= link_to 'Back', metric_types_path %>

app/views/metric_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @metric_type.name %>
</p>


<%= link_to 'Edit', edit_metric_type_path(@metric_type) %> |
<%= link_to 'Back', metric_types_path %>